project:
  title: "Inquinamento Acustico in Acquabella"
  preview:
    port: 4200
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - img/
    - fonts/
    - js/
    - style/
    - R/
  
format:
  html:
    theme: style/custom.scss
    toc: true
    number-sections: true

knitr:
  opts_chunk: 
    dev: jpeg
