---
title: "Inquinamento Acustico in Acquabella"
subtitle: "Un esperimento di citizen science di quartiere."
author: 
  - Otho Mantegazza
  - Caterina Ricci
date: today
editor_options: 
  chunk_output_type: console
---

# Intro

# Setup

```{r}
#| warning: false
library(dplyr, warn.conflicts = FALSE)
library(readr)
library(purrr)
library(ggplot2)
library(lubridate)
library(here)
library(janitor)
```

```{r}
data_folder <- 'data'
function_folder <- 'R'

theme_base <- 
    theme(
    plot.margin = margin(10,5,5,5),
    axis.ticks = element_line(),
    axis.line = element_line(),
    legend.position = "top",
    legend.box = "vertical"
  )

a <- theme_set(
  theme_minimal(
    base_size = 15,
  ) +
    theme_base
)

# source all functions
list.files(
  function_folder,
  full.names = T
) %>% 
  walk(source)
```


# Read Data

```{r}
#| message: false
#| warning: false
noise <- 
  list.dirs(
    data_folder,
    recursive = F
  ) %>% 
  map(read_noise)
```

# View Data

```{r}
#| message: false
#| warning: false
#| column: screen
#| out-width: 100%
#| fig-width: 15
p <- 
  ggplot() +
  aes(x = timestamp,
      y = sound_pressure_level_d_b,
      group = pause_group)

for(noise_record in noise) {
  p <- 
    p +
    geom_line(
      data = noise_record,
      alpha = .2
    ) +
    stat_smooth(
      data = noise_record, 
      method = "loess",
      colour = '#22756d',
      n = 1000,
      span = .1
    )
}

p
```

